import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {BODIES,pickBody,checkPlan,safeResult,tokenCost,accepted,normalizeInput,candidateModels} from '../src/core.mjs';
const plan={goal:'Answer',constraints:[],assumptions:[],criteria:[{id:'C1',requirement:'Answer'}],steps:[{id:'S1',instructions:'Answer',depends_on:[],criteria_ids:['C1'],eligible_models:['qwen','luna'],expected_output_tokens:1024}],assembly_instructions:'Return complete answer'};
const result={answer:'Fixture answer',artifacts:[{path:'answer.txt',content:'Fixture'}],uncertainties:[]};
const review={criteria:[{id:'C1',passed:true,evidence:'Present'}],approved:true,feedback:[]};
test('lowest eligible cost, context fit, no silent truncation',()=>{assert.equal(pickBody(BODIES,['qwen','luna'],1000,1024).id,'qwen');assert.equal(pickBody(BODIES,['qwen','luna'],40000,1024).id,'luna');assert.throws(()=>pickBody(BODIES,['qwen'],40000,1024));});
test('blueprint coverage and dependencies validated',()=>{checkPlan(plan,BODIES);const p=structuredClone(plan);p.steps[0].depends_on=['missing'];assert.throws(()=>checkPlan(p,BODIES));p.steps[0].depends_on=[];p.steps[0].criteria_ids=[];assert.throws(()=>checkPlan(p,BODIES));});
test('all criteria required and unsafe artifact paths rejected',()=>{assert(accepted(review,plan));assert.throws(()=>accepted({...review,criteria:[]},plan));for(const path of ['../secret','/etc/file','.env','dir/../file'])assert.throws(()=>safeResult({...result,artifacts:[{path,content:''}]}));});
test('unknown usage is not free; cached rates applied',()=>{assert.equal(tokenCost(null,BODIES[0].rates),null);assert.equal(tokenCost({input_tokens:1000,output_tokens:1000,cached_input_tokens:0},BODIES[0].rates),.000391);assert.throws(()=>normalizeInput({brief:'x',config:{max_calls:100}}));assert.throws(()=>candidateModels({routing:'manual',body:{backend:'chat',model:'x',base_url:'http://localhost:1234/v1'}}));});
// Import the actual Worker implementation with only platform and provider seams replaced.
const dir=await mkdtemp(tmpdir()+'/acenet-worker-test-');
let source=await readFile(new URL('../src/index.js',import.meta.url),'utf8');source=source.replace("import {DurableObject} from 'cloudflare:workers';","class DurableObject {}").replace("'./assets.generated.mjs'",JSON.stringify(new URL('../src/assets.generated.mjs',import.meta.url).href)).replace("'./core.mjs'",JSON.stringify(new URL('../src/core.mjs',import.meta.url).href)).replace('await modelCall(this.env,','await this.env.TEST_MODEL_CALL(this.env,');await writeFile(dir+'/worker.mjs',source);const {Workspace,default:worker}=await import(pathToFileURL(dir+'/worker.mjs'));
class Storage{map=new Map();async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}async setAlarm(v){this.alarm=v;}async deleteAlarm(){this.alarm=null;}async list({prefix}){return new Map([...this.map].filter(([k])=>k.startsWith(prefix)));}async transaction(fn){return fn(this);}}
function fixture(responses=[plan,result,review]){const storage=new Storage();const env={APP_PASSWORD:'test-password',STORAGE_KEY:'test-encryption-key',TEST_MODEL_CALL:async()=>({text:JSON.stringify(responses.shift()),usage:{input_tokens:100,output_tokens:100,cached_input_tokens:0}})};const ws=new Workspace({storage},env);return {storage,env,ws};}
async function prepared(responses){const f=fixture(responses);await f.storage.put('keys',await f.ws.seal({api_key:'TEST_ONLY'}));return f;}
test('complete 3-call pipeline retains source, routing, cost and acceptance',async()=>{const {ws,storage}=await prepared();const {id}=await ws.start({brief:'Original task',context:[{name:'data.txt',content:'Original data'}]});for(let i=0;i<3;i++)await ws.alarm();const r=await storage.get('run:'+id);assert.equal(r.report.status,'accepted_by_astra');assert.equal(r.source.context[0].content,'Original data');assert.equal(r.ledger.length,3);assert.equal(r.ledger[1].model,BODIES[0].model);assert(r.report.total_cost_usd>0);assert(!JSON.stringify(r).includes('TEST_ONLY'));});
test('review failures repair once then remain unaccepted',async()=>{const fail={criteria:[{id:'C1',passed:false,evidence:'Missing'}],approved:false,feedback:['Fix it']};const {ws,storage}=await prepared([plan,result,fail,result,fail]);const {id}=await ws.start({brief:'task'});for(let i=0;i<5;i++)await ws.alarm();assert.equal((await storage.get('run:'+id)).report.status,'needs_human_review');});
test('malformed paid output fails with usage retained',async()=>{const {ws,storage}=await prepared([{}]);const {id}=await ws.start({brief:'task'});await ws.alarm();const r=await storage.get('run:'+id);assert.equal(r.report.status,'failed');assert(r.report.total_cost_usd>0);});
test('interrupted requests are not replayed',async()=>{const {ws,storage}=await prepared();const {id}=await ws.start({brief:'task'});const r=await storage.get('run:'+id);r.pending=true;await storage.put('run:'+id,r);await ws.alarm();assert.equal((await storage.get('run:'+id)).report.status,'failed');});
test('private APIs reject anonymous access and hostile origins',async()=>{const env={APP_PASSWORD:'p',STORAGE_KEY:'s'};assert.equal((await worker.fetch(new Request('https://example.test/api/runs'),env)).status,401);assert.equal((await worker.fetch(new Request('https://example.test/api/setup',{method:'POST',headers:{Origin:'https://evil.test'}}),env)).status,400);assert.equal((await worker.fetch(new Request('https://example.test/CLAUDE.md'),env)).status,404);});
test('setup encrypts keys and issues session only for correct password',async()=>{const {ws,storage}=fixture();const req=password=>new Request('https://example.test/api/setup',{method:'POST',body:JSON.stringify({password,api_key:'SENSITIVE_TEST_KEY'})});assert.equal((await ws.fetch(req('wrong'))).status,401);const r=await ws.fetch(req('test-password'));assert.equal(r.status,200);assert(r.headers.get('Set-Cookie').includes('HttpOnly; Secure; SameSite=Strict'));assert(!JSON.stringify(await storage.get('keys')).includes('SENSITIVE_TEST_KEY'));assert.equal((await ws.keys()).api_key,'SENSITIVE_TEST_KEY');});
