import {createHash,createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {assert} from './core.mjs';
const json=v=>Response.json(v,{headers:{'Cache-Control':'no-store'}});
const hash=v=>createHash('sha256').update(v).digest();
function encryptionKey(){assert('Account encryption unavailable.',!!process.env.STORAGE_KEY);return hash('acenet-openrouter-v1:'+process.env.STORAGE_KEY);}
export function seal(key,tenant=''){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);cipher.setAAD(Buffer.from(tenant));const data=Buffer.concat([cipher.update(key,'utf8'),cipher.final()]);return {iv:iv.toString('base64'),data:data.toString('base64'),tag:cipher.getAuthTag().toString('base64')};}
export function unseal(value,tenant=''){const cipher=createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(value.iv,'base64'));cipher.setAAD(Buffer.from(tenant));cipher.setAuthTag(Buffer.from(value.tag,'base64'));return Buffer.concat([cipher.update(Buffer.from(value.data,'base64')),cipher.final()]).toString('utf8');}
async function remote(path,options={}){let response;try{response=await fetch('https://openrouter.ai/api/v1/'+path,{...options,redirect:'manual',signal:AbortSignal.timeout(12000)});}catch{throw new Error('OpenRouter could not be reached. Try again.');}if(!response.ok)throw new Error('OpenRouter connection failed ('+response.status+'). Reconnect or try again later.');const text=await response.text();assert('OpenRouter response is too large.',text.length<5000000);return JSON.parse(text);}
export function freeModels(data){return (Array.isArray(data?.data)?data.data:[]).filter(m=>typeof m.id==='string'&&m.id.endsWith(':free')&&m.id.length<160&&m.pricing&&['prompt','completion'].every(k=>m.pricing[k]!==undefined&&m.pricing[k]!==null&&m.pricing[k]!==''&&Number(m.pricing[k])===0)&&Object.values(m.pricing).every(v=>(typeof v==='string'||typeof v==='number')&&v!==''&&Number(v)===0)&&m.architecture?.output_modalities?.includes('text')&&Number.isSafeInteger(m.context_length)&&m.context_length>=8192).map(m=>({id:m.id,name:String(m.name||m.id).slice(0,160),context_length:m.context_length,structured:m.supported_parameters?.includes('structured_outputs')===true})).sort((a,b)=>Number(b.structured)-Number(a.structured)||a.name.localeCompare(b.name));}
let cached=null;
export async function catalog(){if(cached&&Date.now()-cached.at<60000)return cached.models;const models=freeModels(await remote('models'));cached={at:Date.now(),models};return models;}
export async function openrouterStatus(storage){return {connected:!!await storage.get('openrouter-key')};}
export async function openrouterRoute(request,storage){const url=new URL(request.url),p=url.pathname;if(!p.startsWith('/api/account/openrouter/'))return null;const method=request.method;
 if(p.endsWith('/models')&&method==='GET')return json({models:await catalog()});
 if(method!=='POST')return null;
 if(p.endsWith('/start')){const verifier=randomBytes(32).toString('base64url'),state=randomBytes(24).toString('hex');await storage.put('openrouter-pkce',{verifier,state,expires:Date.now()+600000});const callback=new URL('/',url.origin);callback.searchParams.set('or_state',state);const auth=new URL('https://openrouter.ai/auth');auth.searchParams.set('callback_url',callback.href);auth.searchParams.set('code_challenge',hash(verifier).toString('base64url'));auth.searchParams.set('code_challenge_method','S256');return json({url:auth.href});}
 if(p.endsWith('/finish')){const d=await request.json(),pending=await storage.get('openrouter-pkce');assert('OpenRouter connection expired. Start again.',pending&&pending.expires>Date.now()&&typeof d.state==='string'&&d.state===pending.state&&typeof d.code==='string'&&d.code.length>0&&d.code.length<2000);await storage.put('openrouter-pkce',null);const result=await remote('auth/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:d.code,code_verifier:pending.verifier,code_challenge_method:'S256'})});assert('OpenRouter returned no valid key.',typeof result.key==='string'&&result.key.startsWith('sk-or-')&&result.key.length<1024);await storage.put('openrouter-key',seal(result.key,storage.tenant));return json({connected:true});}
 if(p.endsWith('/disconnect')){await storage.put('openrouter-key',null);await storage.put('openrouter-pkce',null);const selection=await storage.get('local-model');if(selection?.server==='openrouter')await storage.put('local-model',null);return json({connected:false});}
 if(p.endsWith('/select')){const d=await request.json();assert('Connect OpenRouter first.',!!await storage.get('openrouter-key'));assert('Select an available free model.',(await catalog()).some(m=>m.id===d.model));await storage.put('local-model',{server:'openrouter',model:d.model});return json({ok:true});}
 return null;
}
export async function openrouterCredential(request,storage){const d=await request.json(),r=typeof d.id==='string'?await storage.get('run:'+d.id):null;assert('Invalid active task claim.',r&&typeof d.claim==='string'&&r.claim===d.claim&&r.report.status==='running'&&r.config.body.backend==='openrouter'&&!await storage.get('bridge-disabled'));const value=await storage.get('openrouter-key');assert('Reconnect OpenRouter in Models.',!!value);return json({key:unseal(value,storage.tenant)});}
