import {unzipSync} from '/vendor/fflate.mjs';
const MAX_TEXT=140000,MAX_FILE=25*1024*1024;
const size=s=>new TextEncoder().encode(s).length;
function xml(bytes){const d=new DOMParser().parseFromString(new TextDecoder().decode(bytes),'application/xml');if(d.querySelector('parsererror'))throw Error('This Office file contains invalid XML.');return d;}
const nodes=(d,name)=>[...d.getElementsByTagNameNS('*',name)];
function archive(bytes){let total=0;return unzipSync(bytes,{filter:f=>{if(!/^(word\/.*\.xml|xl\/.*\.xml|ppt\/slides\/slide\d+\.xml)$/.test(f.name))return false;total+=f.originalSize;if(total>20*1024*1024)throw Error('Expanded document exceeds 20 MB. Export a smaller file.');return true;}});}
function paragraphs(d){return nodes(d,'p').map(p=>nodes(p,'t').map(n=>n.textContent).join('')).join('\n');}
function office(bytes,ext){const z=archive(bytes);
 if(ext==='docx'){if(!z['word/document.xml'])throw Error('This is not a valid DOCX file.');return Object.keys(z).filter(n=>/^word\/(document|header\d+|footer\d+|footnotes|endnotes)\.xml$/.test(n)).sort((a,b)=>(a==='word/document.xml'?-1:b==='word/document.xml'?1:a.localeCompare(b))).map(n=>paragraphs(xml(z[n]))).join('\n');}
 if(ext==='pptx'){const slides=Object.keys(z).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort((a,b)=>Number(a.match(/slide(\d+)/)[1])-Number(b.match(/slide(\d+)/)[1]));if(!slides.length)throw Error('No readable slides found.');return slides.map((n,i)=>'Slide '+(i+1)+'\n'+paragraphs(xml(z[n]))).join('\n\n');}
 if(!z['xl/workbook.xml'])throw Error('This is not a valid XLSX workbook.');const shared=z['xl/sharedStrings.xml']?nodes(xml(z['xl/sharedStrings.xml']),'si').map(n=>nodes(n,'t').map(t=>t.textContent).join('')):[];
 const sheets=Object.keys(z).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort((a,b)=>Number(a.match(/sheet(\d+)/)[1])-Number(b.match(/sheet(\d+)/)[1]));
 return sheets.map(n=>'Worksheet '+n+'\n'+nodes(xml(z[n]),'row').map(row=>nodes(row,'c').map(c=>{const v=nodes(c,'v')[0]?.textContent??'',formula=nodes(c,'f')[0]?.textContent;const value=c.getAttribute('t')==='s'?(shared[Number(v)]??''):c.getAttribute('t')==='inlineStr'?nodes(c,'t').map(t=>t.textContent).join(''):v;return c.getAttribute('r')+': '+value+(formula?' [formula: '+formula+']':'');}).join('\t')).join('\n')).join('\n\n');}
export async function extractFile(file,progress=()=>{}){if(file.size>MAX_FILE)throw Error('Use files under 25 MB.');const ext=file.name.split('.').pop().toLowerCase(),bytes=new Uint8Array(await file.arrayBuffer());let content='';
 if(ext==='pdf'){const pdfjs=await import('/vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdf.worker.mjs';const loading=pdfjs.getDocument({data:bytes,isEvalSupported:false,cMapUrl:'/vendor/cmaps/',cMapPacked:true,standardFontDataUrl:'/vendor/standard_fonts/',wasmUrl:'/vendor/wasm/'});const doc=await loading.promise;try{if(doc.numPages>300)throw Error('Use PDFs with 300 pages or fewer.');for(let page=1;page<=doc.numPages;page++){progress('Reading '+file.name+' · page '+page+' of '+doc.numPages);const text=await (await doc.getPage(page)).getTextContent();content+='\n[Page '+page+']\n'+text.items.map(t=>t.str+(t.hasEOL?'\n':' ')).join('');if(size(content)>MAX_TEXT)throw Error('Extracted text exceeds 140 KB. Split the document into smaller parts.');}if(!content.replace(/\[Page \d+\]/g,'').trim())throw Error('This PDF is scanned or has no text. Export a searchable PDF using OCR first.');}finally{await loading.destroy();}}
 else if(['docx','xlsx','pptx'].includes(ext))content=office(bytes,ext);
 else{if(!/^(txt|md|markdown|csv|tsv|json|jsonl|xml|html?|eml|log|py|js|mjs|ts|tsx|jsx|css|sql|yaml|yml|toml|ini|tex|sh)$/.test(ext))throw Error('Supported: PDF, DOCX, XLSX, PPTX and text/code files. Convert this file to one of these formats.');try{content=new TextDecoder(bytes[0]===255&&bytes[1]===254?'utf-16le':bytes[0]===254&&bytes[1]===255?'utf-16be':'utf-8',{fatal:true}).decode(bytes);}catch{throw Error('This text file uses an unsupported encoding. Save it as UTF-8.');}if(content.includes('\0'))throw Error('This appears to be a binary file, not text.');if(/^html?$/.test(ext)){const d=new DOMParser().parseFromString(content,'text/html');d.querySelectorAll('script,style').forEach(n=>n.remove());content=d.body.textContent;}}
 if(!content.trim())throw Error('No readable text found.');if(size(content)>MAX_TEXT)throw Error('Extracted text exceeds 140 KB. Split the document into smaller parts.');return {name:file.name,content};}
