import test from 'node:test';import assert from 'node:assert/strict';import '../../../app/public/cost-comparison.js';
const {compare,callCost,tokenCost,money,rates}=globalThis.AcenetCosts;
const row=(model='gpt-6-astra',usage={input_tokens:1000,output_tokens:100})=>({model,backend:'codex',role:'execute',status:'completed',usage});
const run=(ledger=[row()])=>({report:{status:'accepted_by_astra'},source:{brief:'x'.repeat(40000)},result:{answer:'y'.repeat(40000)},ledger});
test('savings use the original task/output projection and all harness calls',()=>{const c=compare(run([row(),row('gpt-5.6-luna')]));assert(Math.abs(c.harness-.01532)<1e-10);assert.equal(c.saved,c.traditional-c.harness);assert(c.saved>0);assert.equal(c.calls,2);assert.equal(compare({...run(),report:{status:'running'}}),null);});
test('cache reads and long-context standard rates are applied',()=>{assert.equal(tokenCost({input_tokens:1000,cached_input_tokens:900,output_tokens:100},rates['gpt-6-astra']),.0069);assert.equal(tokenCost({input_tokens:300000,cached_input_tokens:0,output_tokens:100},rates['gpt-6-astra']),6.0075);assert.equal(callCost(row('unknown')),null);assert.equal(callCost(row('gpt-6-astra',{input_tokens:10,output_tokens:1,cached_input_tokens:20})),null);});
test('unknown or incomplete usage never becomes zero savings',()=>{const c=compare(run([row(),row('unknown')]));assert.equal(c.harness,null);assert.equal(c.saved,null);assert.equal(c.missing,1);assert.equal(compare(run([])).saved,null);assert.equal(compare({...run(),result:null}).traditional,null);assert.equal(callCost(row('gpt-6-astra',{input_tokens:-1,output_tokens:1})),null);});
test('extra costs stay negative; failed retries are counted',()=>{const r=run([{...row(),status:'failed'},row()]);r.source={brief:'hi'};r.result={answer:'hi'};const c=compare(r);assert.equal(c.harness,.03);assert(c.saved<0);assert(c.percent<0);assert.equal(money(null),'Unavailable');assert.equal(money(.00001),'<$0.0001');});
test('local and provider-reported Claude amounts have separate bases',()=>{assert.equal(callCost({backend:'chat',billing:'local_model'}),0);assert.equal(callCost({backend:'chat'}),null);assert.equal(callCost({backend:'claude',usage:{api_equivalent_cost_usd:.42}}),.42);assert.equal(callCost({backend:'claude',usage:{input_tokens:100,output_tokens:20}}),null);});
test('hosted free bodies contribute zero only with verified price evidence',()=>{assert.equal(callCost({backend:'openrouter',usage:{free_price_verified:true,api_equivalent_cost_usd:0}}),0);assert.equal(callCost({backend:'openrouter',usage:{}}),null);assert.equal(callCost({backend:'openrouter',usage:{free_price_verified:true,api_equivalent_cost_usd:1}}),null);});
test('recorded Astra baseline replaces projections and direct Astra does not invent savings',()=>{const r=run([row('gpt-5.6-luna')]);r.comparison_baseline={report:{status:'baseline_complete'},ledger:[row()]};const c=compare(r);assert.equal(c.traditional,.015);assert(c.measured);const direct=compare({...run(),report:{status:'baseline_complete',route:'direct_astra'}});assert.equal(direct.saved,0);assert(direct.measured);});
test('native overhead is included where recorded prompt size permits estimation',()=>{const r=run([{...row(),prompt_bytes:400,connectors_enabled:false}]);const c=compare(r);assert.equal(c.overhead,900);assert.equal(c.input,Math.ceil(JSON.stringify(r.source).length/4)+1200);});

test('unsuccessful runs show recorded spend but never savings',()=>{for(const status of ['failed','cancelled','needs_human_review']){const r=run([row()]);r.report.status=status;const c=compare(r);assert.equal(c.harness,.015);assert.equal(c.traditional,null);assert.equal(c.saved,null);assert.equal(c.percent,null);}});
