import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,copyFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(tmpdir()+'/acenet-handler-test-');await copyFile(new URL('../lib/auth.mjs',import.meta.url),dir+'/auth.mjs');
await copyFile(new URL('../lib/pairing.mjs',import.meta.url),dir+'/pairing.mjs');
await copyFile(new URL('../lib/errors.mjs',import.meta.url),dir+'/errors.mjs');
let source=await readFile(new URL('../api/index.mjs',import.meta.url),'utf8');source=source.replace("'../lib/auth.mjs'","'./auth.mjs'").replace("import {planRoute,bridgeRoute} from '../lib/plan.mjs';",`const bridgeRoute=async(r,s)=>Response.json({value:await s.get('marker')||null}); const planRoute=async(r,s)=>new URL(r.url).pathname==='/api/account'?Response.json({value:await s.get('marker')||null}):null;`).replace("import {Workspace} from '../lib/worker.generated.mjs';",`class Workspace{constructor(ctx){this.storage=ctx.storage;}async fetch(r){return Response.json({value:await this.storage.get('marker')||null});}}`).replace("import {Storage,acquire} from '../lib/storage.mjs';",`const map=new Map();export class Storage{constructor(t=''){this.t=t;}async get(k){return map.get(this.t+':'+k);}async put(k,v){map.set(this.t+':'+k,v);}};const acquire=async()=>async()=>globalThis.__acenetEvents.push('release');`);
source=source.replace("'../lib/pairing.mjs'","'./pairing.mjs'").replace("'../lib/errors.mjs'","'./errors.mjs'");
await writeFile(dir+'/handler.mjs',source);const {default:handler,Storage}=await import(pathToFileURL(dir+'/handler.mjs'));
process.env.BLOB_READ_WRITE_TOKEN='test';process.env.BRIDGE_TOKEN='owner-connector';process.env.APP_PASSWORD='owner-password';process.env.STORAGE_KEY='test-storage-secret';
async function call(path,body,cookie='',csrf='',extra={}){globalThis.__acenetEvents=[];const headers={};let result;const res={setHeader(k,v){headers[k]=v;},end(data){globalThis.__acenetEvents.push('response');try{result=JSON.parse(data.toString());}catch{result=data.toString();}}};await handler({url:path,method:body===undefined?'GET':'POST',headers:{host:'app.test',origin:'https://app.test',cookie,'x-acenet-token':csrf,...extra},body},res);return {status:res.statusCode,body:result,cookie:headers['set-cookie']?.split(';')[0]};}
test('accounts, sessions, downloads, cancellations and connector tokens isolate tenants and owner',async()=>{
 await new Storage().put('marker','owner-private');
 const a=await call('/api/auth/register',{username:'alice',password:'a-unique-password'});assert.equal(a.status,200);assert.deepEqual(globalThis.__acenetEvents,['release','response']);
 const b=await call('/api/auth/register',{username:'bravo',password:'b-unique-password'});assert.equal(b.status,200);
 assert.equal((await call('/api/account')).status,401);assert.equal((await call('/api/account',undefined,a.cookie)).body.value,null);
 const ac=await call('/api/account/connector-config',undefined,a.cookie),bc=await call('/api/account/connector-config',undefined,b.cookie);assert.notEqual(ac.body.token,bc.body.token);assert.notEqual(ac.body.token,process.env.BRIDGE_TOKEN);
 const tenant=ac.body.token.split('.')[1];await new Storage(tenant).put('marker','alice-private');
 assert.equal((await call('/api/runs/known-id/download',undefined,b.cookie)).body.value,null);assert.equal((await call('/api/runs/known-id/download',undefined,a.cookie)).body.value,'alice-private');
 assert.equal((await call('/api/bridge/next',{},'', '',{authorization:'Bearer '+ac.body.token})).body.value,'alice-private');assert.deepEqual(globalThis.__acenetEvents,['release','response']);
 assert.equal((await call('/api/bridge/next',{},'', '',{authorization:'Bearer '+bc.body.token})).body.value,null);
 assert.equal((await call('/api/bridge/next',{},'', '',{authorization:'Bearer forged'})).status,401);
 assert.equal((await call('/api/bridge/next',{},'', '',{authorization:'Bearer owner-connector'})).body.value,'owner-private');
 assert.equal((await call('/api/runs/known-id/cancel',{},b.cookie,b.body.token)).status,404);
 assert.equal((await call('/api/auth/logout',{},a.cookie,'wrong')).status,401);
 assert.equal((await call('/api/auth/logout',{},a.cookie,a.body.token,{origin:'https://evil.test'})).status,403);
 assert.equal((await call('/api/auth/logout',{},a.cookie,a.body.token)).status,200);assert.equal((await call('/api/account',undefined,a.cookie)).status,401);
 assert.equal((await call('/api/auth/login',{username:'alice',password:'a-unique-password'})).status,200);
 assert.equal((await call('/api/auth/login',{username:'alice',password:'wrong'})).status,401);
 const owner=await call('/api/setup',{password:'owner-password'});assert.equal((await call('/api/account',undefined,owner.cookie)).body.value,'owner-private');
});
test('pairing requires the account session and CSRF, redeems only once without browser origin, and preserves the owner',async()=>{
 const user=await call('/api/auth/register',{username:'pairing-user',password:'pairing-user-password'},'','',{'x-vercel-forwarded-for':'192.0.2.55'});
 assert.equal(user.status,200);
 assert.equal((await call('/api/account/pairing',{})).status,401);
 assert.equal((await call('/api/account/pairing',{},user.cookie,'wrong')).status,401);
 assert.equal((await call('/api/account/pairing',{},user.cookie,user.body.token,{origin:'https://evil.test'})).status,403);
 assert.equal((await call('/api/account/pairing',undefined,user.cookie)).status,405);
 const issued=await call('/api/account/pairing',{tenant:''},user.cookie,user.body.token);
 assert.equal(issued.status,200);assert.deepEqual(globalThis.__acenetEvents,['release','response']);
 assert.match(issued.body.code,/^[A-F0-9]{24}$/);assert.equal(issued.body.token,undefined);
 const redeemed=await call('/api/pair/redeem',{code:issued.body.code,tenant:'',app:'https://evil.test'},'','',{origin:undefined,host:'untrusted.test','x-vercel-forwarded-for':'192.0.2.56'});
 assert.equal(redeemed.status,200);assert.equal(redeemed.body.app,'https://acenet-zeta.vercel.app');assert.notEqual(redeemed.body.token,process.env.BRIDGE_TOKEN);
 assert.deepEqual(globalThis.__acenetEvents,['release','response']);
 const config=await call('/api/account/connector-config',undefined,user.cookie);assert.equal(redeemed.body.token,config.body.token);
 assert.equal((await call('/api/pair/redeem',{code:issued.body.code},'','',{origin:undefined,'x-vercel-forwarded-for':'192.0.2.56'})).status,400);
 assert.equal((await call('/api/pair/redeem',undefined)).status,405);
 const owner=await call('/api/setup',{password:'owner-password'},'','',{'x-vercel-forwarded-for':'192.0.2.57'});
 const ownerCode=await call('/api/account/pairing',{},owner.cookie,owner.body.token);
 const ownerConfig=await call('/api/pair/redeem',{code:ownerCode.body.code},'','',{origin:undefined,'x-vercel-forwarded-for':'192.0.2.58'});
 assert.equal(ownerConfig.status,200);assert.equal(ownerConfig.body.token,process.env.BRIDGE_TOKEN);
});
