import test from 'node:test';import assert from 'node:assert/strict';import {planConfig,planRoute,bridgeRoute} from '../lib/plan.mjs';
class Store{m=new Map();async get(k){return structuredClone(this.m.get(k));}async put(k,v){this.m.set(k,structuredClone(v));}}
const req=(p,d)=>new Request('https://app.test'+p,{method:'POST',body:JSON.stringify(d)});
test('plan mode cannot choose API backends even when supplied',()=>{const c=planConfig({backend:'responses',model:'other'});assert.equal(c.brain.backend,'codex');assert.equal(c.body.backend,'codex');assert.equal(c.body.model,'gpt-5.6-luna');assert.equal(c.brain.rates,null);assert.throws(()=>planConfig({backend:'chat',base_url:'https://paid-provider.test/v1',model:'x'}));});
test('offline account blocks tasks; queue claimed once and original source survives updates',async()=>{const s=new Store();await assert.rejects(()=>planRoute(req('/api/runs',{brief:'task'}),s));await s.put('bridge',{signed_in:true,harness_version:2,seen:Date.now()});const started=await planRoute(req('/api/runs',{brief:'Original task'}),s);const {id}=await started.json();const claimed=await bridgeRoute(req('/api/bridge/next',{connector_id:'test',signed_in:true,harness_version:2}),s);const r=(await claimed.json()).run;assert.equal(r.id,id);assert.equal((await (await bridgeRoute(req('/api/bridge/next',{connector_id:'test',signed_in:true,harness_version:2}),s)).json()).run,null);await bridgeRoute(req('/api/bridge/progress',{id,claim:r.claim,detail:{ledger:[],report:{status:'failed'},source:{brief:'tampered'}}}),s);assert.equal((await s.get('run:'+id)).source.brief,'Original task');assert.equal((await s.get('run:'+id)).report.billing,'chatgpt_plan');});
test('tick endpoint cannot charge an API key',async()=>{assert.equal((await planRoute(req('/api/tick',{}),new Store())).status,409);});
test('Claude-only accounts get honest native model routing without Codex calls',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:2,seen:Date.now(),providers:{claude:true,chatgpt:false}});const {id}=await (await planRoute(req('/api/runs',{brief:'Claude task',provider:'auto'}),s)).json();const r=await s.get('run:'+id);assert.equal(r.config.brain.backend,'claude');assert.equal(r.config.body.model,'haiku');assert.equal(r.report.billing,'claude_account');});
test('unconnected or unsupported subscriptions cannot silently use another account',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:2,seen:Date.now(),providers:{claude:true,chatgpt:false}});await assert.rejects(()=>planRoute(req('/api/runs',{brief:'Task',provider:'chatgpt'}),s));await assert.rejects(()=>planRoute(req('/api/runs',{brief:'Task',provider:'gemini'}),s));});
test('explicit baseline links to its original run and uses Astra without the selected body',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:2,seen:Date.now(),providers:{chatgpt:true}});await s.put('run:original',{id:'original',source:{brief:'Original task',context:[]},report:{status:'accepted_by_astra'}});await s.put('local-model',{server:'ollama',model:'missing'});const {id}=await (await planRoute(req('/api/runs/original/baseline',{}),s)).json();const r=await s.get('run:'+id);assert.equal(r.baseline_of,'original');assert.equal(r.config.brain.model,'gpt-6-astra');assert.equal((await s.get('run:original')).baseline_id,id);assert.equal(r.mode,'baseline');});
