import test from 'node:test';import assert from 'node:assert/strict';import {planConfig,planRoute,bridgeRoute} from '../lib/plan.mjs';
class Store{m=new Map();async get(k){return structuredClone(this.m.get(k));}async put(k,v){this.m.set(k,structuredClone(v));}}
const req=(p,d)=>new Request('https://app.test'+p,{method:'POST',body:JSON.stringify(d)});
test('Astra is mandatory and native fallback is rejected',()=>{assert.throws(()=>planConfig());assert.throws(()=>planConfig({backend:'responses',model:'other'}));const c=planConfig({backend:'chat',base_url:'http://127.0.0.1:11434/v1',model:'qwen'},'claude');assert.equal(c.brain.model,'gpt-6-astra');assert.equal(c.body.model,'qwen');assert.equal(c.source_provider,'claude');assert.equal(c.execution_policy,'astra-orchestrator-v3');});
test('offline account blocks tasks; queue claimed once and original source survives updates',async()=>{const s=new Store();await assert.rejects(()=>planRoute(req('/api/runs',{brief:'task'}),s));await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now()});const started=await planRoute(req('/api/runs',{brief:'Original task',body:{backend:'chat',model:'qwen',base_url:'http://127.0.0.1:11434/v1'}}),s);const {id}=await started.json();const claimed=await bridgeRoute(req('/api/bridge/next',{connector_id:'test',signed_in:true,harness_version:3}),s);const r=(await claimed.json()).run;assert.equal(r.id,id);assert.equal((await (await bridgeRoute(req('/api/bridge/next',{connector_id:'test',signed_in:true,harness_version:3}),s)).json()).run,null);await bridgeRoute(req('/api/bridge/progress',{id,claim:r.claim,detail:{ledger:[],report:{status:'failed'},source:{brief:'tampered'}}}),s);assert.equal((await s.get('run:'+id)).source.brief,'Original task');assert.equal((await s.get('run:'+id)).report.billing,'chatgpt_plan');});
test('tick endpoint cannot charge an API key',async()=>{assert.equal((await planRoute(req('/api/tick',{}),new Store())).status,409);});
test('Claude-only account cannot replace Astra',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now(),providers:{claude:true,chatgpt:false}});await assert.rejects(()=>planRoute(req('/api/runs',{brief:'Task',provider:'claude'}),s),/Astra/);});
test('unconnected or unsupported subscriptions cannot silently use another account',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now(),providers:{claude:true,chatgpt:false}});await assert.rejects(()=>planRoute(req('/api/runs',{brief:'Task',provider:'chatgpt'}),s));await assert.rejects(()=>planRoute(req('/api/runs',{brief:'Task',provider:'gemini'}),s));});
test('explicit baseline links to its original run and uses Astra without the selected body',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now(),providers:{chatgpt:true}});await s.put('run:original',{id:'original',source:{brief:'Original task',context:[]},report:{status:'accepted_by_astra'}});await s.put('local-model',{server:'ollama',model:'missing'});const {id}=await (await planRoute(req('/api/runs/original/baseline',{}),s)).json();const r=await s.get('run:'+id);assert.equal(r.baseline_of,'original');assert.equal(r.config.brain.model,'gpt-6-astra');assert.equal((await s.get('run:original')).baseline_id,id);assert.equal(r.mode,'baseline');});

test('no configured open executor cannot queue or spend',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now(),providers:{chatgpt:true}});const response=await planRoute(req('/api/runs',{brief:'task'}),s);assert.equal(response.status,400);assert.equal((await response.json()).code,'executor_setup_required');assert.equal(await s.get('active'),undefined);});

test('follow-up uses only same-tenant conversation and preserves prior messages and files',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now(),providers:{chatgpt:true}});await s.put('run:first',{id:'first',title:'First',source:{brief:'Use GBP',context:[{name:'data.txt',content:'42'}]},user_message:'Use GBP',result:{answer:'GBP 42',artifacts:[]},report:{status:'accepted_by_astra'}});const body={backend:'chat',model:'qwen',base_url:'http://127.0.0.1:11434/v1'};await assert.rejects(()=>planRoute(req('/api/runs',{brief:'Continue',parent_id:'other-tenant-id',body}),s),/Conversation not found/);const {id}=await (await planRoute(req('/api/runs',{brief:'Double it',parent_id:'first',body}),s)).json();const run=await s.get('run:'+id);assert.equal(run.conversation_id,'first');assert.equal(run.user_message,'Double it');assert(run.source.brief.includes('Use GBP'));assert(run.source.brief.includes('GBP 42'));assert.equal(run.source.context[0].content,'42');assert.equal(run.config.current_message,'Double it');});
test('new chat contains no prior history',async()=>{const s=new Store();await s.put('bridge',{signed_in:true,harness_version:3,seen:Date.now(),providers:{chatgpt:true}});const {id}=await (await planRoute(req('/api/runs',{brief:'New question',body:{backend:'chat',model:'qwen',base_url:'http://127.0.0.1:11434/v1'}}),s)).json();const run=await s.get('run:'+id);assert.deepEqual(run.turns,[]);assert.equal(run.source.brief,'New question');});
